// Generated by LiveScript 1.2.0
(function(){
  var Parallel;
  Parallel = (function(){
    Parallel.displayName = 'Parallel';
    var prototype = Parallel.prototype, constructor = Parallel;
    function Parallel(len, cb){
      this.len = len;
      this.cb = cb;
      if (this.len === 0) {
        this.cb();
      }
    }
    prototype.queue = function(){
      return ++this.len;
    };
    prototype.done = function(){
      if (--this.len === 0) {
        return this.cb();
      }
    };
    return Parallel;
  }());
  module.exports = Parallel;
}).call(this);
